apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          {{- with .Values.command }}
          command:
            {{- range . }}
            - {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- range . }}
            - {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom: {{ include "custom.envFrom" $ | indent 8 }}
          {{- with .livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- range .Values.initContainers }}
        {{- if or .enabled (eq .enabled nil) }}
        - name: {{ include "common.tplvalues.render" (dict "value" .name "context" $) }}
          image: {{ include "common.tplvalues.render" (dict "value" (required "Image repository is required." .image.repository) "context" $) }}:{{ include "common.tplvalues.render" (dict "value" (required "Image tag is required." .image.tag) "context" $) }}
          imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
          envFrom: {{ include "custom.envFrom" $ | indent 8 }}
          {{- with .command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
