{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
data:
  {{- range .data }}
    {{ include "common.tplvalues.render" (dict "value" .name "context" $) }}: {{ include "common.tplvalues.render" (dict "value" .value "context" $) | b64enc }}
  {{- end }}
---
{{- end }}
